# Generated by Django 6.0.3 on 2026-03-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
            ],
        ),
    ]
